# Generated by Django 6.0.3 on 2026-04-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_alter_user_username_auditlog_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization'], name='accounts_br_organiz_f8285b_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='accounts_br_code_dce7de_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='accounts_br_is_acti_ddea38_idx'),
        ),
    ]
