# Generated by Django 6.0.3 on 2026-04-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription_grace_period_days_and_more'),
        ('attend', '0001_initial'),
        ('student', '0002_student_student_stu_branch__602349_idx_and_more'),
        ('teacher', '0002_teacher_teacher_tea_branch__713a6f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['branch', 'date'], name='attend_atte_branch__a78fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attend_atte_student_d3a675_idx'),
        ),
    ]
