# Generated by Django 6.0.3 on 2026-04-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0003_subscription_grace_period_days_and_more'),
        ('teacher', '0002_teacher_teacher_tea_branch__713a6f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['branch', 'name'], name='academics_a_branch__287f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='classsection',
            index=models.Index(fields=['branch'], name='academics_c_branch__771d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='classsection',
            index=models.Index(fields=['class_level'], name='academics_c_class_l_349f26_idx'),
        ),
    ]
